### ISSUE TITLE
crafttweaker error when opening world

### ISSUE THREAD

**Issue by otakup0pe** [ReadOnly-Mods/Galacticraft-Pack#18]
## Bug Description

When loading a world, either new or from a save, the following crafttweaker error is generated from `Tinker.zs`

```
[10:59:46] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] <A7>cERROR: CraftTweaker\Tinkers.zs:4 > No such member: Melting
[10:59:46] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] <A7>cERROR: [crafttweaker]: Error executing {[0:crafttweaker]: CraftTweaker\Tinkers.zs}: Truncated class file, caused by java.lang.ClassFormatError: Truncated class file
```

### Did this work in the previous version?

unknown (first time playing)

## Steps to Reproduce (for bugs)

1. Open world (either saved or new)

## Logs

* Client Log: [gist](https://gist.github.com/otakup0pe/f17d021a8cffb9d080f4abe9985cab77)
* Crash Log: n/a

## Client Information

* Modpack Version: 3.3.1
* Launcher Used: MultiMC 0.6.14-3001
* Java Version: `jre1.8.0_311`
* Memory Allocated: `-Xms512m, -Xmx8096m`
* Server/LAN/Single Player: Single Player
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.3.1
* Additional Content Installed: no

**Comment by ROMVoid95** [comment]
If you are able too still, send the file called `crafttweaker.log` that's located in the root directory of the instance.

**Comment by otakup0pe** [comment]
Finally got around to this. Pertinent message seems to be

```
[INITIALIZATION][CLIENT][ERROR] CraftTweaker\Tinkers.zs:4 > No such member: Melting
[INITIALIZATION][CLIENT][ERROR] [crafttweaker]: Error executing {[0:crafttweaker]: CraftTweaker\Tinkers.zs}: Truncated class file
java.lang.ClassFormatError: Truncated class file
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at stanhebben.zenscript.ZenModule$MyClassLoader.loadClass(ZenModule.java:419)
        at CraftTweaker\Tinkers.__script__(CraftTweaker\Tinkers.zs:4)
        at __ZenMain__.run(CraftTweaker\Tinkers)
        at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:240)
        at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:105)
        at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:71)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_959_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
        at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
        at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
        at net.minecraft.client.main.Main.main(SourceFile:123)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
        at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
        at org.multimc.EntryPoint.listen(EntryPoint.java:143)
        at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by ROMVoid95** [comment]
The script in question was removed from the pack a few updates ago. So you can simply update the pack or delete the Tinker.zs file located at `\scripts\CraftTweaker\Tinkers.zs`
